# Site settings
title: jh.cv
email: ralwnsgus4715@gmail.com
url: https://github.com/krex4715/krex4715.github.io/
description: "AI Robot Engineer J.H. Kim Homepage"
meta_author: J. H. Kim


# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)

color:
  primary: 05a35f #80B3FF
  primary_head: bfd2d9 # headline
  primary_res: e2e3de # research
  primary_awa: f1faeb # award
  primary_pub: dfeff0 # award
  primary-rgb: "128,179,0" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F







# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  social: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: fa-brands fa-fw fa-github
    url: http://github.com/krex4715
  - title: fa fa-bold
    url: https://roboharco12.tistory.com/
  - title: fa-brands fa-fw fa-instagram
    url: https://www.instagram.com/anvry_jh/


# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
